allMatches = [
  {
    home: ["Martin"],
    games: [
      { home: 4, away: 11 },
      { home: 8, away: 11 },
    ],
    away: ["Fridtjof"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Cem"],
    games: [
      { home: 2, away: 11 },
      { home: 3, away: 11 },
    ],
    away: ["Stefan"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Jasmin"],
    games: [
      { home: 11, away: 0 },
      { home: 11, away: 2 },
    ],
    away: ["Pengyang"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Frederik"],
    games: [
      { home: 10, away: 11 },
      { home: 6, away: 11 },
    ],
    away: ["Basti"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Sandra"],
    games: [
      { home: 11, away: 7 },
      { home: 11, away: 3 },
    ],
    away: ["Ria"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Zhenqiang"],
    games: [
      { home: 11, away: 3 },
      { home: 11, away: 5 },
    ],
    away: ["Eli"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Fengjie"],
    games: [
      { home: 11, away: 7 },
      { home: 6, away: 11 },
      { home: 11, away: 4 },
    ],
    away: ["Sarosh"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Sven"],
    games: [
      { home: 6, away: 11 },
      { home: 11, away: 8 },
      { home: 7, away: 11 },
    ],
    away: ["Hansi"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Tuan"],
    games: [
      { home: 6, away: 11 },
      { home: 11, away: 9 },
      { home: 9, away: 11 },
    ],
    away: ["Marvin"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Peng"],
    games: [
      { home: 2, away: 11 },
      { home: 9, away: 11 },
    ],
    away: ["Torben"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Fridtjof"],
    games: [
      { home: 11, away: 2 },
      { home: 11, away: 3 },
    ],
    away: ["Pengyang"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Sarosh"],
    games: [
      { home: 11, away: 7 },
      { home: 11, away: 7 },
    ],
    away: ["Martin"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Ria"],
    games: [
      { home: 7, away: 11 },
      { home: 2, away: 11 },
    ],
    away: ["Peng"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Marvin"],
    games: [
      { home: 6, away: 11 },
      { home: 10, away: 11 },
    ],
    away: ["Torben"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Hansi"],
    games: [
      { home: 11, away: 9 },
      { home: 11, away: 4 },
    ],
    away: ["Sandra"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Tuan"],
    games: [
      { home: 11, away: 9 },
      { home: 7, away: 11 },
      { home: 11, away: 7 },
    ],
    away: ["Sven"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Jasmin"],
    games: [
      { home: 5, away: 11 },
      { home: 3, away: 11 },
    ],
    away: ["Stefan"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Eli"],
    games: [
      { home: 11, away: 1 },
      { home: 11, away: 5 },
    ],
    away: ["Cem"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Frederik"],
    games: [
      { home: 6, away: 11 },
      { home: 6, away: 11 },
    ],
    away: ["Zhenqiang"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Fengjie"],
    games: [
      { home: 10, away: 11 },
      { home: 11, away: 6 },
      { home: 11, away: 10 },
    ],
    away: ["Basti"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Jasmin"],
    games: [
      { home: 9, away: 11 },
      { home: 9, away: 11 },
    ],
    away: ["Hansi"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Stefan"],
    games: [
      { home: 11, away: 8 },
      { home: 10, away: 11 },
      { home: 9, away: 11 },
    ],
    away: ["Basti"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Fridtjof"],
    games: [
      { home: 11, away: 6 },
      { home: 7, away: 11 },
      { home: 9, away: 11 },
    ],
    away: ["Sandra"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Fengjie"],
    games: [
      { home: 6, away: 11 },
      { home: 3, away: 11 },
    ],
    away: ["Torben"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Zhenqiang"],
    games: [
      { home: 11, away: 2 },
      { home: 11, away: 6 },
    ],
    away: ["Tuan"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Sven"],
    games: [
      { home: 11, away: 1 },
      { home: 11, away: 0 },
    ],
    away: ["Pengyang"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Marvin"],
    games: [
      { home: 11, away: 7 },
      { home: 11, away: 9 },
    ],
    away: ["Frederik"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Ria"],
    games: [
      { home: 6, away: 11 },
      { home: 0, away: 11 },
    ],
    away: ["Sarosh"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Eli"],
    games: [
      { home: 6, away: 11 },
      { home: 10, away: 11 },
    ],
    away: ["Peng"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Cem"],
    games: [
      { home: 4, away: 11 },
      { home: 5, away: 11 },
    ],
    away: ["Martin"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Torben"],
    games: [
      { home: 11, away: 5 },
      { home: 11, away: 6 },
    ],
    away: ["Zhenqiang"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Stefan"],
    games: [
      { home: 11, away: 10 },
      { home: 8, away: 11 },
      { home: 7, away: 11 },
    ],
    away: ["Fengjie"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Tuan"],
    games: [
      { home: 6, away: 11 },
      { home: 11, away: 9 },
      { home: 6, away: 11 },
    ],
    away: ["Hansi"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Fridtjof"],
    games: [
      { home: 11, away: 6 },
      { home: 11, away: 8 },
    ],
    away: ["Jasmin"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Eli"],
    games: [
      { home: 11, away: 9 },
      { home: 11, away: 7 },
    ],
    away: ["Sandra"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Basti"],
    games: [
      { home: 8, away: 11 },
      { home: 11, away: 5 },
      { home: 10, away: 11 },
    ],
    away: ["Peng"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Sven"],
    games: [
      { home: 5, away: 11 },
      { home: 7, away: 11 },
    ],
    away: ["Sarosh"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Martin"],
    games: [
      { home: 0, away: 11 },
      { home: 11, away: 10 },
      { home: 9, away: 11 },
    ],
    away: ["Marvin"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Pengyang"],
    games: [
      { home: 1, away: 11 },
      { home: 0, away: 11 },
    ],
    away: ["Frederik"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Cem"],
    games: [
      { home: 8, away: 11 },
      { home: 11, away: 10 },
      { home: 9, away: 11 },
    ],
    away: ["Ria"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Torben"],
    games: [
      { home: 11, away: 7 },
      { home: 11, away: 7 },
    ],
    away: ["Hansi"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Fengjie"],
    games: [
      { home: 7, away: 11 },
      { home: 5, away: 11 },
    ],
    away: ["Zhenqiang"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Peng"],
    games: [
      { home: 11, away: 9 },
      { home: 10, away: 11 },
      { home: 11, away: 8 },
    ],
    away: ["Sandra"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Basti"],
    games: [
      { home: 11, away: 7 },
      { home: 11, away: 5 },
    ],
    away: ["Tuan"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Sven"],
    games: [
      { home: 8, away: 11 },
      { home: 5, away: 11 },
    ],
    away: ["Fridtjof"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Stefan"],
    games: [
      { home: 5, away: 11 },
      { home: 5, away: 11 },
    ],
    away: ["Sarosh"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Eli"],
    games: [
      { home: 6, away: 11 },
      { home: 5, away: 11 },
    ],
    away: ["Martin"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Marvin"],
    games: [
      { home: 11, away: 7 },
      { home: 11, away: 1 },
    ],
    away: ["Jasmin"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Pengyang"],
    games: [
      { home: 5, away: 11 },
      { home: 3, away: 11 },
    ],
    away: ["Cem"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Frederik"],
    games: [
      { home: 11, away: 2 },
      { home: 11, away: 9 },
    ],
    away: ["Ria"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Hansi"],
    games: [
      { home: 6, away: 11 },
      { home: 11, away: 4 },
      { home: 5, away: 11 },
    ],
    away: ["Torben"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Sarosh"],
    games: [
      { home: 2, away: 11 },
      { home: 6, away: 11 },
    ],
    away: ["Zhenqiang"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Fengjie"],
    games: [
      { home: 11, away: 7 },
      { home: 11, away: 5 },
    ],
    away: ["Peng"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Fridtjof"],
    games: [
      { home: 7, away: 11 },
      { home: 11, away: 10 },
      { home: 11, away: 5 },
    ],
    away: ["Sandra"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Basti"],
    games: [
      { home: 7, away: 11 },
      { home: 10, away: 11 },
    ],
    away: ["Marvin"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Eli"],
    games: [
      { home: 10, away: 11 },
      { home: 9, away: 11 },
    ],
    away: ["Sven"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Jasmin"],
    games: [
      { home: 11, away: 3 },
      { home: 11, away: 5 },
    ],
    away: ["Ria"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Frederik"],
    games: [
      { home: 11, away: 2 },
      { home: 11, away: 9 },
    ],
    away: ["Martin"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Cem"],
    games: [
      { home: 11, away: 4 },
      { home: 11, away: 3 },
    ],
    away: ["Pengyang"],
    date: "2021.09.03 Einzel",
  },
  {
    home: ["Basti"],
    games: [
      { home: 11, away: 7 },
      { home: 11, away: 8 },
    ],
    away: ["Hansi"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Arne"],
    games: [
      { home: 10, away: 11 },
      { home: 10, away: 11 },
    ],
    away: ["Martin"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Jasmin"],
    games: [
      { home: 11, away: 7 },
      { home: 10, away: 11 },
      { home: 10, away: 11 },
    ],
    away: ["Sandra"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Weicheng"],
    games: [
      { home: 11, away: 7 },
      { home: 11, away: 4 },
    ],
    away: ["Torben"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Hanno"],
    games: [
      { home: 6, away: 11 },
      { home: 3, away: 11 },
    ],
    away: ["Fridtjof"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Bengt"],
    games: [
      { home: 6, away: 11 },
      { home: 4, away: 11 },
    ],
    away: ["Zhenqiang"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Qingyue"],
    games: [
      { home: 5, away: 11 },
      { home: 4, away: 11 },
    ],
    away: ["Melf"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Marvin"],
    games: [
      { home: 11, away: 5 },
      { home: 11, away: 7 },
    ],
    away: ["Tuan"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Hansi"],
    games: [
      { home: 4, away: 11 },
      { home: 1, away: 11 },
    ],
    away: ["Weicheng"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Zhenqiang"],
    games: [
      { home: 11, away: 10 },
      { home: 11, away: 10 },
    ],
    away: ["Sandra"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Melf"],
    games: [
      { home: 11, away: 8 },
      { home: 11, away: 9 },
    ],
    away: ["Jasmin"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Bengt"],
    games: [
      { home: 8, away: 11 },
      { home: 6, away: 11 },
    ],
    away: ["Torben"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Vinh"],
    games: [
      { home: 11, away: 7 },
      { home: 8, away: 11 },
      { home: 11, away: 8 },
    ],
    away: ["Martin"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Basti"],
    games: [
      { home: 8, away: 11 },
      { home: 11, away: 8 },
      { home: 11, away: 9 },
    ],
    away: ["Fridtjof"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Hanno"],
    games: [
      { home: 9, away: 11 },
      { home: 11, away: 6 },
      { home: 6, away: 11 },
    ],
    away: ["Arne"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Qingyue"],
    games: [
      { home: 5, away: 11 },
      { home: 11, away: 7 },
      { home: 4, away: 11 },
    ],
    away: ["Tuan"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Fridtjof"],
    games: [
      { home: 11, away: 9 },
      { home: 11, away: 3 },
    ],
    away: ["Sandra"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Zhenqiang"],
    games: [
      { home: 11, away: 6 },
      { home: 10, away: 11 },
      { home: 7, away: 11 },
    ],
    away: ["Basti"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Weicheng"],
    games: [
      { home: 11, away: 9 },
      { home: 11, away: 0 },
    ],
    away: ["Marvin"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Melf"],
    games: [
      { home: 11, away: 1 },
      { home: 8, away: 11 },
      { home: 11, away: 9 },
    ],
    away: ["Martin"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Hansi"],
    games: [
      { home: 4, away: 11 },
      { home: 5, away: 11 },
    ],
    away: ["Vinh"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Hanno"],
    games: [
      { home: 10, away: 11 },
      { home: 11, away: 8 },
      { home: 10, away: 11 },
    ],
    away: ["Jasmin"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Bengt"],
    games: [
      { home: 2, away: 11 },
      { home: 4, away: 11 },
    ],
    away: ["Tuan"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Arne"],
    games: [
      { home: 9, away: 11 },
      { home: 11, away: 6 },
      { home: 11, away: 6 },
    ],
    away: ["Qingyue"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Aditya"],
    games: [
      { home: 11, away: 0 },
      { home: 11, away: 3 },
    ],
    away: ["Pengyang"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Marvin"],
    games: [
      { home: 7, away: 11 },
      { home: 11, away: 9 },
      { home: 10, away: 11 },
    ],
    away: ["Basti"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Weicheng"],
    games: [
      { home: 11, away: 5 },
      { home: 11, away: 5 },
    ],
    away: ["Zhenqiang"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Melf"],
    games: [
      { home: 4, away: 11 },
      { home: 8, away: 11 },
    ],
    away: ["Vinh"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Martin"],
    games: [
      { home: 9, away: 11 },
      { home: 5, away: 11 },
    ],
    away: ["Aditya"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Pengyang"],
    games: [
      { home: 0, away: 11 },
      { home: 3, away: 11 },
    ],
    away: ["Torben"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Fridtjof"],
    games: [
      { home: 11, away: 6 },
      { home: 11, away: 6 },
    ],
    away: ["Arne"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Sandra"],
    games: [
      { home: 11, away: 6 },
      { home: 11, away: 6 },
    ],
    away: ["Tuan"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Jasmin"],
    games: [
      { home: 11, away: 8 },
      { home: 11, away: 10 },
    ],
    away: ["Hansi"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Qingyue"],
    games: [
      { home: 11, away: 9 },
      { home: 8, away: 11 },
      { home: 11, away: 9 },
    ],
    away: ["Bengt"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Melf"],
    games: [
      { home: 10, away: 11 },
      { home: 9, away: 11 },
    ],
    away: ["Basti"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Vinh"],
    games: [
      { home: 8, away: 11 },
      { home: 4, away: 11 },
    ],
    away: ["Weicheng"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Zhenqiang"],
    games: [
      { home: 9, away: 11 },
      { home: 11, away: 8 },
      { home: 11, away: 9 },
    ],
    away: ["Aditya"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Arne"],
    games: [
      { home: 11, away: 0 },
      { home: 11, away: 2 },
    ],
    away: ["Tuan"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Marvin"],
    games: [
      { home: 10, away: 11 },
      { home: 5, away: 11 },
    ],
    away: ["Fridtjof"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Martin"],
    games: [
      { home: 5, away: 11 },
      { home: 4, away: 11 },
    ],
    away: ["Torben"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Jasmin"],
    games: [
      { home: 11, away: 5 },
      { home: 11, away: 10 },
    ],
    away: ["Sandra"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Hanno"],
    games: [
      { home: 11, away: 9 },
      { home: 10, away: 11 },
      { home: 11, away: 8 },
    ],
    away: ["Hansi"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Pengyang"],
    games: [
      { home: 4, away: 11 },
      { home: 2, away: 11 },
    ],
    away: ["Qingyue"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Basti"],
    games: [
      { home: 11, away: 8 },
      { home: 8, away: 11 },
      { home: 11, away: 8 },
    ],
    away: ["Vinh"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Aditya"],
    games: [
      { home: 6, away: 11 },
      { home: 3, away: 11 },
    ],
    away: ["Weicheng"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Fridtjof"],
    games: [
      { home: 9, away: 11 },
      { home: 9, away: 11 },
    ],
    away: ["Melf"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Torben"],
    games: [
      { home: 11, away: 8 },
      { home: 5, away: 11 },
      { home: 11, away: 5 },
    ],
    away: ["Zhenqiang"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Jasmin"],
    games: [
      { home: 6, away: 11 },
      { home: 11, away: 9 },
      { home: 7, away: 11 },
    ],
    away: ["Tuan"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Sandra"],
    games: [
      { home: 10, away: 11 },
      { home: 11, away: 3 },
      { home: 11, away: 9 },
    ],
    away: ["Arne"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Marvin"],
    games: [
      { home: 6, away: 11 },
      { home: 11, away: 6 },
      { home: 11, away: 4 },
    ],
    away: ["Martin"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Pengyang"],
    games: [
      { home: 4, away: 11 },
      { home: 5, away: 11 },
    ],
    away: ["Qingyue"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Hanno"],
    games: [
      { home: 11, away: 8 },
      { home: 11, away: 3 },
    ],
    away: ["Bengt"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Fridtjof"],
    games: [
      { home: 11, away: 9 },
      { home: 11, away: 4 },
    ],
    away: ["Vinh"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Torben"],
    games: [
      { home: 11, away: 8 },
      { home: 11, away: 8 },
    ],
    away: ["Aditya"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Martin"],
    games: [
      { home: 11, away: 8 },
      { home: 11, away: 10 },
    ],
    away: ["Melf"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Arne"],
    games: [
      { home: 10, away: 11 },
      { home: 11, away: 6 },
      { home: 9, away: 11 },
    ],
    away: ["Jasmin"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Marvin"],
    games: [
      { home: 11, away: 6 },
      { home: 11, away: 9 },
    ],
    away: ["Qingyue"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Sandra"],
    games: [
      { home: 7, away: 11 },
      { home: 4, away: 11 },
    ],
    away: ["Tuan"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Hansi"],
    games: [
      { home: 6, away: 11 },
      { home: 8, away: 11 },
    ],
    away: ["Hanno"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Pengyang"],
    games: [
      { home: 5, away: 11 },
      { home: 1, away: 11 },
    ],
    away: ["Bengt"],
    date: "2021.11.12 Einzel",
  },
  {
    home: ["Martin", "Qian"],
    games: [{ home: 7, away: 11 }],
    away: ["Stefan", "Sven"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Martin", "Stefan"],
    games: [{ home: 11, away: 10 }],
    away: ["Qian", "Sven"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Martin", "Sven"],
    games: [{ home: 6, away: 11 }],
    away: ["Qian", "Stefan"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Zhenqiang", "Sina"],
    games: [{ home: 11, away: 6 }],
    away: ["Ria", "Sandra"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Zhenqiang", "Ria"],
    games: [{ home: 10, away: 11 }],
    away: ["Sina", "Sandra"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Zhenqiang", "Sandra"],
    games: [{ home: 11, away: 7 }],
    away: ["Sina", "Ria"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Melf", "Tobi"],
    games: [{ home: 5, away: 11 }],
    away: ["Eli", "Basti"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Melf", "Eli"],
    games: [{ home: 11, away: 10 }],
    away: ["Tobi", "Basti"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Melf", "Basti"],
    games: [{ home: 11, away: 5 }],
    away: ["Tobi", "Eli"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Rui", "Sarosh"],
    games: [{ home: 6, away: 11 }],
    away: ["Robin", "Peng"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Rui", "Robin"],
    games: [{ home: 6, away: 11 }],
    away: ["Sarosh", "Peng"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Rui", "Peng"],
    games: [{ home: 5, away: 11 }],
    away: ["Sarosh", "Robin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Hanno", "Jasmin"],
    games: [{ home: 8, away: 11 }],
    away: ["Fengjie", "Hansi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Hanno", "Fengjie"],
    games: [{ home: 11, away: 8 }],
    away: ["Jasmin", "Hansi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Hanno", "Hansi"],
    games: [{ home: 10, away: 11 }],
    away: ["Jasmin", "Fengjie"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Verena"],
    games: [{ home: 3, away: 11 }],
    away: ["Marvin", "Fridtjof"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Marvin"],
    games: [{ home: 11, away: 9 }],
    away: ["Verena", "Fridtjof"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Fridtjof"],
    games: [{ home: 4, away: 11 }],
    away: ["Verena", "Marvin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Peng"],
    games: [{ home: 11, away: 4 }],
    away: ["Qian", "Eli"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Qian"],
    games: [{ home: 11, away: 9 }],
    away: ["Peng", "Eli"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Eli"],
    games: [{ home: 6, away: 11 }],
    away: ["Peng", "Qian"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Melf", "Zhenqiang"],
    games: [{ home: 11, away: 5 }],
    away: ["Sven", "Robin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Melf", "Sven"],
    games: [{ home: 8, away: 11 }],
    away: ["Zhenqiang", "Robin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Melf", "Robin"],
    games: [{ home: 11, away: 6 }],
    away: ["Zhenqiang", "Sven"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Tobi", "Ria"],
    games: [{ home: 2, away: 11 }],
    away: ["Marvin", "Fengjie"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Tobi", "Marvin"],
    games: [{ home: 8, away: 11 }],
    away: ["Ria", "Fengjie"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Tobi", "Fengjie"],
    games: [{ home: 11, away: 8 }],
    away: ["Ria", "Marvin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sarosh", "Verena"],
    games: [{ home: 11, away: 6 }],
    away: ["Vinh", "Hansi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sarosh", "Vinh"],
    games: [{ home: 11, away: 7 }],
    away: ["Verena", "Hansi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sarosh", "Hansi"],
    games: [{ home: 11, away: 2 }],
    away: ["Verena", "Vinh"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sina", "Hanno"],
    games: [{ home: 8, away: 11 }],
    away: ["Stefan", "Rui"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sina", "Stefan"],
    games: [{ home: 8, away: 11 }],
    away: ["Hanno", "Rui"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sina", "Rui"],
    games: [{ home: 9, away: 11 }],
    away: ["Hanno", "Stefan"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sandra", "Jasmin"],
    games: [{ home: 11, away: 9 }],
    away: ["Martin", "Franzi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sandra", "Martin"],
    games: [{ home: 11, away: 6 }],
    away: ["Jasmin", "Franzi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sandra", "Franzi"],
    games: [{ home: 11, away: 7 }],
    away: ["Jasmin", "Martin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fengjie", "Zhenqiang"],
    games: [{ home: 11, away: 4 }],
    away: ["Stefan", "Marvin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fengjie", "Stefan"],
    games: [{ home: 9, away: 11 }],
    away: ["Zhenqiang", "Marvin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fengjie", "Marvin"],
    games: [{ home: 5, away: 11 }],
    away: ["Zhenqiang", "Stefan"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Peng", "Robin"],
    games: [{ home: 11, away: 8 }],
    away: ["Sandra", "Basti"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Peng", "Sandra"],
    games: [{ home: 6, away: 11 }],
    away: ["Robin", "Basti"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Peng", "Basti"],
    games: [{ home: 11, away: 6 }],
    away: ["Robin", "Sandra"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sina", "Melf"],
    games: [{ home: 5, away: 11 }],
    away: ["Eli", "Sarosh"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sina", "Eli"],
    games: [{ home: 2, away: 11 }],
    away: ["Melf", "Sarosh"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sina", "Sarosh"],
    games: [{ home: 11, away: 3 }],
    away: ["Melf", "Eli"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sven", "Fridtjof"],
    games: [{ home: 9, away: 11 }],
    away: ["Vinh", "Hanno"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sven", "Vinh"],
    games: [{ home: 8, away: 11 }],
    away: ["Fridtjof", "Hanno"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sven", "Hanno"],
    games: [{ home: 8, away: 11 }],
    away: ["Fridtjof", "Vinh"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Martin"],
    games: [{ home: 11, away: 7 }],
    away: ["Hansi", "Rui"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Hansi"],
    games: [{ home: 11, away: 5 }],
    away: ["Martin", "Rui"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Rui"],
    games: [{ home: 6, away: 11 }],
    away: ["Martin", "Hansi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Ria", "Jasmin"],
    games: [{ home: 6, away: 11 }],
    away: ["Qian", "Verena"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Ria", "Qian"],
    games: [{ home: 11, away: 9 }],
    away: ["Jasmin", "Verena"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Ria", "Verena"],
    games: [{ home: 3, away: 11 }],
    away: ["Jasmin", "Qian"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sandra", "Fengjie"],
    games: [{ home: 4, away: 11 }],
    away: ["Sarosh", "Stefan"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sandra", "Sarosh"],
    games: [{ home: 11, away: 6 }],
    away: ["Fengjie", "Stefan"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sandra", "Stefan"],
    games: [{ home: 9, away: 11 }],
    away: ["Fengjie", "Sarosh"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Zhenqiang", "Peng"],
    games: [{ home: 8, away: 11 }],
    away: ["Marvin", "Robin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Zhenqiang", "Marvin"],
    games: [{ home: 6, away: 11 }],
    away: ["Peng", "Robin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Zhenqiang", "Robin"],
    games: [{ home: 11, away: 4 }],
    away: ["Peng", "Marvin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Basti"],
    games: [{ home: 11, away: 7 }],
    away: ["Hanno", "Melf"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Hanno"],
    games: [{ home: 5, away: 11 }],
    away: ["Basti", "Melf"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Melf"],
    games: [{ home: 9, away: 11 }],
    away: ["Basti", "Hanno"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Eli", "Rui"],
    games: [{ home: 3, away: 11 }],
    away: ["Qian", "Sina"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Eli", "Qian"],
    games: [{ home: 7, away: 11 }],
    away: ["Rui", "Sina"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Eli", "Sina"],
    games: [{ home: 11, away: 7 }],
    away: ["Rui", "Qian"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Sven"],
    games: [{ home: 11, away: 10 }],
    away: ["Hansi", "Jasmin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Hansi"],
    games: [{ home: 11, away: 7 }],
    away: ["Sven", "Jasmin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Jasmin"],
    games: [{ home: 4, away: 11 }],
    away: ["Sven", "Hansi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Vinh", "Tobi"],
    games: [{ home: 10, away: 11 }],
    away: ["Verena", "Martin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Vinh", "Verena"],
    games: [{ home: 11, away: 10 }],
    away: ["Tobi", "Martin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Vinh", "Martin"],
    games: [{ home: 11, away: 4 }],
    away: ["Tobi", "Verena"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Peng", "Zhenqiang"],
    games: [{ home: 10, away: 11 }],
    away: ["Sarosh", "Fengjie"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Peng", "Sarosh"],
    games: [{ home: 11, away: 7 }],
    away: ["Zhenqiang", "Fengjie"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Peng", "Fengjie"],
    games: [{ home: 11, away: 10 }],
    away: ["Zhenqiang", "Sarosh"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Basti", "Stefan"],
    games: [{ home: 11, away: 7 }],
    away: ["Robin", "Qian"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Basti", "Robin"],
    games: [{ home: 11, away: 8 }],
    away: ["Stefan", "Qian"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Basti", "Qian"],
    games: [{ home: 11, away: 10 }],
    away: ["Stefan", "Robin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Marvin", "Martin"],
    games: [{ home: 8, away: 11 }],
    away: ["Melf", "Hanno"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Marvin", "Melf"],
    games: [{ home: 11, away: 8 }],
    away: ["Martin", "Hanno"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Marvin", "Hanno"],
    games: [{ home: 11, away: 10 }],
    away: ["Martin", "Melf"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Hansi"],
    games: [{ home: 11, away: 7 }],
    away: ["Sandra", "Vinh"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Sandra"],
    games: [{ home: 11, away: 9 }],
    away: ["Hansi", "Vinh"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Vinh"],
    games: [{ home: 8, away: 11 }],
    away: ["Hansi", "Sandra"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Eli"],
    games: [{ home: 10, away: 11 }],
    away: ["Verena", "Sina"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Verena"],
    games: [{ home: 5, away: 11 }],
    away: ["Eli", "Sina"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Sina"],
    games: [{ home: 4, away: 11 }],
    away: ["Eli", "Verena"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Ria", "Tobi"],
    games: [{ home: 11, away: 8 }],
    away: ["Jasmin", "Rui"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Ria", "Jasmin"],
    games: [{ home: 10, away: 11 }],
    away: ["Tobi", "Rui"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Ria", "Rui"],
    games: [{ home: 8, away: 11 }],
    away: ["Tobi", "Jasmin"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sarosh", "Robin"],
    games: [{ home: 2, away: 11 }],
    away: ["Zhenqiang", "Basti"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sarosh", "Zhenqiang"],
    games: [{ home: 11, away: 6 }],
    away: ["Robin", "Basti"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sarosh", "Basti"],
    games: [{ home: 11, away: 3 }],
    away: ["Robin", "Zhenqiang"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Qian", "Fengjie"],
    games: [{ home: 11, away: 7 }],
    away: ["Stefan", "Peng"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Qian", "Stefan"],
    games: [{ home: 3, away: 11 }],
    away: ["Fengjie", "Peng"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Qian", "Peng"],
    games: [{ home: 11, away: 9 }],
    away: ["Fengjie", "Stefan"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Vinh", "Marvin"],
    games: [{ home: 9, away: 11 }],
    away: ["Melf", "Sandra"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Vinh", "Melf"],
    games: [{ home: 11, away: 7 }],
    away: ["Marvin", "Sandra"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Vinh", "Sandra"],
    games: [{ home: 6, away: 11 }],
    away: ["Marvin", "Melf"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Martin"],
    games: [{ home: 11, away: 7 }],
    away: ["Hansi", "Sina"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Hansi"],
    games: [{ home: 11, away: 9 }],
    away: ["Martin", "Sina"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Fridtjof", "Sina"],
    games: [{ home: 11, away: 5 }],
    away: ["Martin", "Hansi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Hanno"],
    games: [{ home: 11, away: 10 }],
    away: ["Verena", "Eli"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Verena"],
    games: [{ home: 4, away: 11 }],
    away: ["Hanno", "Eli"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Franzi", "Eli"],
    games: [{ home: 8, away: 11 }],
    away: ["Hanno", "Verena"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sven", "Rui"],
    games: [{ home: 11, away: 10 }],
    away: ["Tobi", "Ria"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sven", "Tobi"],
    games: [{ home: 11, away: 2 }],
    away: ["Rui", "Ria"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Sven", "Ria"],
    games: [{ home: 11, away: 8 }],
    away: ["Rui", "Tobi"],
    date: "2021.07.30 Doppel",
  },
  {
    home: ["Thomas", "Sandra"],
    games: [{ home: 6, away: 11 }],
    away: ["Vinh", "Frederik"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Thomas", "Vinh"],
    games: [{ home: 9, away: 11 }],
    away: ["Sandra", "Frederik"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Thomas", "Frederik"],
    games: [{ home: 11, away: 5 }],
    away: ["Sandra", "Vinh"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Melf", "Tuan"],
    games: [{ home: 11, away: 10 }],
    away: ["Torben", "Eli"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Melf", "Torben"],
    games: [{ home: 11, away: 6 }],
    away: ["Tuan", "Eli"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Melf", "Eli"],
    games: [{ home: 7, away: 11 }],
    away: ["Tuan", "Torben"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Sina", "Marvin"],
    games: [{ home: 11, away: 1 }],
    away: ["Pengyang", "Jasmin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Sina", "Pengyang"],
    games: [{ home: 3, away: 11 }],
    away: ["Marvin", "Jasmin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Sina", "Jasmin"],
    games: [{ home: 11, away: 2 }],
    away: ["Marvin", "Pengyang"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Ria"],
    games: [{ home: 5, away: 11 }],
    away: ["Verena", "Qian"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Verena"],
    games: [{ home: 8, away: 11 }],
    away: ["Ria", "Qian"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Qian"],
    games: [{ home: 11, away: 2 }],
    away: ["Ria", "Verena"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Tuan"],
    games: [{ home: 11, away: 2 }],
    away: ["Sandra", "Pengyang"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Sandra"],
    games: [{ home: 11, away: 4 }],
    away: ["Tuan", "Pengyang"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Pengyang"],
    games: [{ home: 5, away: 11 }],
    away: ["Tuan", "Sandra"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Sina", "Verena"],
    games: [{ home: 6, away: 11 }],
    away: ["Frederik", "Vinh"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Sina", "Frederik"],
    games: [{ home: 9, away: 11 }],
    away: ["Verena", "Vinh"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Sina", "Vinh"],
    games: [{ home: 11, away: 3 }],
    away: ["Verena", "Frederik"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Eli", "Torben"],
    games: [{ home: 11, away: 2 }],
    away: ["Ria", "Jasmin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Eli", "Ria"],
    games: [{ home: 6, away: 11 }],
    away: ["Torben", "Jasmin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Eli", "Jasmin"],
    games: [{ home: 7, away: 11 }],
    away: ["Torben", "Ria"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Melf", "Thomas"],
    games: [{ home: 11, away: 8 }],
    away: ["Qian", "Marvin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Melf", "Qian"],
    games: [{ home: 6, away: 11 }],
    away: ["Thomas", "Marvin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Melf", "Marvin"],
    games: [{ home: 11, away: 6 }],
    away: ["Thomas", "Qian"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Melf", "Qian"],
    games: [{ home: 10, away: 11 }],
    away: ["Frederik", "Marvin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Melf", "Frederik"],
    games: [{ home: 11, away: 6 }],
    away: ["Qian", "Marvin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Melf", "Marvin"],
    games: [{ home: 10, away: 11 }],
    away: ["Qian", "Frederik"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Torben", "Sina"],
    games: [{ home: 11, away: 6 }],
    away: ["Tuan", "Jasmin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Torben", "Tuan"],
    games: [{ home: 11, away: 7 }],
    away: ["Sina", "Jasmin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Torben", "Jasmin"],
    games: [{ home: 11, away: 9 }],
    away: ["Sina", "Tuan"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Pengyang"],
    games: [{ home: 5, away: 11 }],
    away: ["Vinh", "Eli"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Vinh"],
    games: [{ home: 11, away: 2 }],
    away: ["Pengyang", "Eli"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Eli"],
    games: [{ home: 11, away: 2 }],
    away: ["Pengyang", "Vinh"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Verena", "Ria"],
    games: [{ home: 5, away: 11 }],
    away: ["Sandra", "Thomas"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Verena", "Sandra"],
    games: [{ home: 11, away: 8 }],
    away: ["Ria", "Thomas"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Verena", "Thomas"],
    games: [{ home: 11, away: 5 }],
    away: ["Ria", "Sandra"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Marvin", "Frederik"],
    games: [{ home: 22, away: 20 }],
    away: ["Melf", "Torben"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Marvin", "Melf"],
    games: [{ home: 16, away: 21 }],
    away: ["Frederik", "Torben"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Marvin", "Torben"],
    games: [{ home: 30, away: 29 }],
    away: ["Frederik", "Melf"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Tuan", "Sina"],
    games: [{ home: 16, away: 21 }],
    away: ["Vinh", "Qian"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Tuan", "Vinh"],
    games: [{ home: 21, away: 13 }],
    away: ["Sina", "Qian"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Tuan", "Qian"],
    games: [{ home: 21, away: 12 }],
    away: ["Sina", "Vinh"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Jasmin", "Thomas"],
    games: [{ home: 21, away: 12 }],
    away: ["Sandra", "Hanno"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Jasmin", "Sandra"],
    games: [{ home: 23, away: 21 }],
    away: ["Thomas", "Hanno"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Jasmin", "Hanno"],
    games: [{ home: 25, away: 23 }],
    away: ["Thomas", "Sandra"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Verena", "Ria"],
    games: [{ home: 21, away: 17 }],
    away: ["Eli", "Pengyang"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Verena", "Eli"],
    games: [{ home: 21, away: 13 }],
    away: ["Ria", "Pengyang"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Verena", "Pengyang"],
    games: [{ home: 11, away: 21 }],
    away: ["Ria", "Eli"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Vinh", "Frederik"],
    games: [{ home: 18, away: 21 }],
    away: ["Marvin", "Torben"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Vinh", "Marvin"],
    games: [{ home: 16, away: 21 }],
    away: ["Frederik", "Torben"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Vinh", "Torben"],
    games: [{ home: 19, away: 21 }],
    away: ["Frederik", "Marvin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Thomas", "Tuan"],
    games: [{ home: 22, away: 24 }],
    away: ["Jasmin", "Qian"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Thomas", "Jasmin"],
    games: [{ home: 21, away: 19 }],
    away: ["Tuan", "Qian"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Thomas", "Qian"],
    games: [{ home: 22, away: 24 }],
    away: ["Tuan", "Jasmin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Sandra"],
    games: [{ home: 19, away: 21 }],
    away: ["Verena", "Melf"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Verena"],
    games: [{ home: 17, away: 21 }],
    away: ["Sandra", "Melf"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Melf"],
    games: [{ home: 21, away: 18 }],
    away: ["Sandra", "Verena"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Eli", "Ria"],
    games: [{ home: 22, away: 20 }],
    away: ["Pengyang", "Sina"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Eli", "Pengyang"],
    games: [{ home: 9, away: 21 }],
    away: ["Ria", "Sina"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Eli", "Sina"],
    games: [{ home: 21, away: 6 }],
    away: ["Ria", "Pengyang"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Frederik", "Jasmin"],
    games: [{ home: 7, away: 11 }],
    away: ["Torben", "Marvin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Frederik", "Torben"],
    games: [{ home: 10, away: 11 }],
    away: ["Jasmin", "Marvin"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Frederik", "Marvin"],
    games: [{ home: 11, away: 6 }],
    away: ["Jasmin", "Torben"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Thomas", "Tuan"],
    games: [{ home: 11, away: 9 }],
    away: ["Melf", "Vinh"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Thomas", "Melf"],
    games: [{ home: 10, away: 11 }],
    away: ["Tuan", "Vinh"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Thomas", "Vinh"],
    games: [{ home: 5, away: 11 }],
    away: ["Tuan", "Melf"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Pengyang", "Ria"],
    games: [{ home: 4, away: 11 }],
    away: ["Qian", "Sandra"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Pengyang", "Qian"],
    games: [{ home: 5, away: 11 }],
    away: ["Ria", "Sandra"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Pengyang", "Sandra"],
    games: [{ home: 9, away: 11 }],
    away: ["Ria", "Qian"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Sina"],
    games: [{ home: 11, away: 5 }],
    away: ["Verena", "Eli"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Verena"],
    games: [{ home: 8, away: 11 }],
    away: ["Sina", "Eli"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Hanno", "Eli"],
    games: [{ home: 9, away: 11 }],
    away: ["Sina", "Verena"],
    date: "2021.10.08 Doppel",
  },
  {
    home: ["Basti", "Hanno"],
    games: [{ home: 11, away: 4 }],
    away: ["Pengyang", "Ria"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Pengyang"],
    games: [{ home: 9, away: 11 }],
    away: ["Hanno", "Ria"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Ria"],
    games: [{ home: 11, away: 3 }],
    away: ["Hanno", "Pengyang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Sina", "Verena"],
    games: [{ home: 9, away: 11 }],
    away: ["Vinh", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Sina", "Vinh"],
    games: [{ home: 8, away: 11 }],
    away: ["Verena", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Sina", "Zhenqiang"],
    games: [{ home: 11, away: 5 }],
    away: ["Verena", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Frederik"],
    games: [{ home: 8, away: 11 }],
    away: ["Martin", "Qian"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Martin"],
    games: [{ home: 7, away: 11 }],
    away: ["Frederik", "Qian"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Qian"],
    games: [{ home: 1, away: 11 }],
    away: ["Frederik", "Martin"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Qingyue", "Sandra"],
    games: [{ home: 1, away: 11 }],
    away: ["Torben", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Qingyue", "Torben"],
    games: [{ home: 10, away: 11 }],
    away: ["Sandra", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Qingyue", "Tuan"],
    games: [{ home: 11, away: 10 }],
    away: ["Sandra", "Torben"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Frederik"],
    games: [{ home: 11, away: 0 }],
    away: ["Hanno", "Qingyue"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Hanno"],
    games: [{ home: 11, away: 10 }],
    away: ["Frederik", "Qingyue"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Qingyue"],
    games: [{ home: 7, away: 11 }],
    away: ["Frederik", "Hanno"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Melf", "Pengyang"],
    games: [{ home: 5, away: 11 }],
    away: ["Torben", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Melf", "Torben"],
    games: [{ home: 11, away: 2 }],
    away: ["Pengyang", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Melf", "Verena"],
    games: [{ home: 11, away: 9 }],
    away: ["Pengyang", "Torben"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Martin"],
    games: [{ home: 3, away: 11 }],
    away: ["Ria", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Ria"],
    games: [{ home: 3, away: 11 }],
    away: ["Martin", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Sina"],
    games: [{ home: 7, away: 11 }],
    away: ["Martin", "Ria"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Qian", "Tuan"],
    games: [{ home: 5, away: 11 }],
    away: ["Vinh", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Qian", "Vinh"],
    games: [{ home: 10, away: 11 }],
    away: ["Tuan", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Qian", "Zhenqiang"],
    games: [{ home: 11, away: 1 }],
    away: ["Tuan", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Frederik"],
    games: [{ home: 11, away: 4 }],
    away: ["Martin", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Martin"],
    games: [{ home: 11, away: 7 }],
    away: ["Frederik", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Tuan"],
    games: [{ home: 11, away: 8 }],
    away: ["Frederik", "Martin"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Hanno", "Qian"],
    games: [{ home: 8, away: 11 }],
    away: ["Ria", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Hanno", "Ria"],
    games: [{ home: 5, away: 11 }],
    away: ["Qian", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Hanno", "Zhenqiang"],
    games: [{ home: 11, away: 4 }],
    away: ["Qian", "Ria"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Melf"],
    games: [{ home: 11, away: 6 }],
    away: ["Qingyue", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Qingyue"],
    games: [{ home: 11, away: 8 }],
    away: ["Melf", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Verena"],
    games: [{ home: 4, away: 11 }],
    away: ["Melf", "Qingyue"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Sandra", "Sina"],
    games: [{ home: 9, away: 11 }],
    away: ["Torben", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Sandra", "Torben"],
    games: [{ home: 11, away: 4 }],
    away: ["Sina", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Sandra", "Vinh"],
    games: [{ home: 6, away: 11 }],
    away: ["Sina", "Torben"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Frederik"],
    games: [{ home: 11, away: 4 }],
    away: ["Ria", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Ria"],
    games: [{ home: 10, away: 11 }],
    away: ["Frederik", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Zhenqiang"],
    games: [{ home: 11, away: 6 }],
    away: ["Frederik", "Ria"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Hanno", "Martin"],
    games: [{ home: 11, away: 4 }],
    away: ["Qingyue", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Hanno", "Qingyue"],
    games: [{ home: 10, away: 11 }],
    away: ["Martin", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Hanno", "Tuan"],
    games: [{ home: 7, away: 11 }],
    away: ["Martin", "Qingyue"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Cem"],
    games: [{ home: 6, away: 11 }],
    away: ["Verena", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Verena"],
    games: [{ home: 11, away: 8 }],
    away: ["Cem", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Vinh"],
    games: [{ home: 11, away: 3 }],
    away: ["Cem", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Melf", "Pengyang"],
    games: [{ home: 4, away: 11 }],
    away: ["Sandra", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Melf", "Sandra"],
    games: [{ home: 11, away: 5 }],
    away: ["Pengyang", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Melf", "Sina"],
    games: [{ home: 11, away: 3 }],
    away: ["Pengyang", "Sandra"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Martin"],
    games: [{ home: 11, away: 10 }],
    away: ["Torben", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Torben"],
    games: [{ home: 11, away: 5 }],
    away: ["Martin", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Vinh"],
    games: [{ home: 10, away: 11 }],
    away: ["Martin", "Torben"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Hanno"],
    games: [{ home: 11, away: 4 }],
    away: ["Ria", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Ria"],
    games: [{ home: 11, away: 7 }],
    away: ["Hanno", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Tuan"],
    games: [{ home: 11, away: 7 }],
    away: ["Hanno", "Ria"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Cem"],
    games: [{ home: 11, away: 9 }],
    away: ["Pengyang", "Sandra"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Pengyang"],
    games: [{ home: 10, away: 11 }],
    away: ["Cem", "Sandra"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Sandra"],
    games: [{ home: 11, away: 3 }],
    away: ["Cem", "Pengyang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Melf", "Qian"],
    games: [{ home: 11, away: 1 }],
    away: ["Qingyue", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Melf", "Qingyue"],
    games: [{ home: 4, away: 11 }],
    away: ["Qian", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Melf", "Sina"],
    games: [{ home: 11, away: 7 }],
    away: ["Qian", "Qingyue"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Martin"],
    games: [{ home: 7, away: 11 }],
    away: ["Melf", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Melf"],
    games: [{ home: 11, away: 6 }],
    away: ["Martin", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Tuan"],
    games: [{ home: 11, away: 8 }],
    away: ["Martin", "Melf"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Hanno"],
    games: [{ home: 11, away: 8 }],
    away: ["Torben", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Torben"],
    games: [{ home: 11, away: 5 }],
    away: ["Hanno", "Zhenqiang"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Zhenqiang"],
    games: [{ home: 7, away: 11 }],
    away: ["Hanno", "Torben"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Pengyang"],
    games: [{ home: 4, away: 11 }],
    away: ["Qian", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Qian"],
    games: [{ home: 11, away: 5 }],
    away: ["Pengyang", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Vinh"],
    games: [{ home: 11, away: 9 }],
    away: ["Pengyang", "Qian"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Ria"],
    games: [{ home: 2, away: 11 }],
    away: ["Sandra", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Sandra"],
    games: [{ home: 11, away: 4 }],
    away: ["Ria", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Verena"],
    games: [{ home: 11, away: 4 }],
    away: ["Ria", "Sandra"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Torben"],
    games: [{ home: 7, away: 11 }],
    away: ["Tuan", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Tuan"],
    games: [{ home: 9, away: 11 }],
    away: ["Torben", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Vinh"],
    games: [{ home: 8, away: 11 }],
    away: ["Torben", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Hanno"],
    games: [{ home: 6, away: 11 }],
    away: ["Martin", "Melf"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Martin"],
    games: [{ home: 10, away: 11 }],
    away: ["Hanno", "Melf"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Melf"],
    games: [{ home: 11, away: 7 }],
    away: ["Hanno", "Martin"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Ria"],
    games: [{ home: 9, away: 11 }],
    away: ["Sandra", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Sandra"],
    games: [{ home: 11, away: 4 }],
    away: ["Ria", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Aditya", "Verena"],
    games: [{ home: 11, away: 9 }],
    away: ["Ria", "Sandra"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Pengyang"],
    games: [{ home: 10, away: 11 }],
    away: ["Qingyue", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Qingyue"],
    games: [{ home: 10, away: 11 }],
    away: ["Pengyang", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Sina"],
    games: [{ home: 11, away: 4 }],
    away: ["Pengyang", "Qingyue"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Melf"],
    games: [{ home: 11, away: 10 }],
    away: ["Torben", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Torben"],
    games: [{ home: 10, away: 11 }],
    away: ["Melf", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Tuan"],
    games: [{ home: 9, away: 11 }],
    away: ["Melf", "Torben"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Hanno"],
    games: [{ home: 7, away: 11 }],
    away: ["Sandra", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Sandra"],
    games: [{ home: 3, away: 11 }],
    away: ["Hanno", "Vinh"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Vinh"],
    games: [{ home: 6, away: 11 }],
    away: ["Hanno", "Sandra"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Pengyang", "Ria"],
    games: [{ home: 7, away: 11 }],
    away: ["Sina", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Pengyang", "Sina"],
    games: [{ home: 9, away: 11 }],
    away: ["Ria", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Pengyang", "Verena"],
    games: [{ home: 7, away: 11 }],
    away: ["Ria", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Hanno"],
    games: [{ home: 4, away: 11 }],
    away: ["Sina", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Sina"],
    games: [{ home: 7, away: 11 }],
    away: ["Hanno", "Tuan"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Cem", "Tuan"],
    games: [{ home: 2, away: 11 }],
    away: ["Hanno", "Sina"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Aditya"],
    games: [{ home: 7, away: 11 }],
    away: ["Melf", "Torben"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Melf"],
    games: [{ home: 9, away: 11 }],
    away: ["Aditya", "Torben"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Basti", "Torben"],
    games: [{ home: 11, away: 6 }],
    away: ["Aditya", "Melf"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Martin"],
    games: [{ home: 11, away: 8 }],
    away: ["Sandra", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Sandra"],
    games: [{ home: 11, away: 7 }],
    away: ["Martin", "Verena"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Frederik", "Verena"],
    games: [{ home: 11, away: 9 }],
    away: ["Martin", "Sandra"],
    date: "2021.12.03 Doppel",
  },
  {
    home: ["Torben", "Basti"],
    games: [{ home: 9, away: 11 }],
    away: ["Georg", "Meik"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Torben", "Georg"],
    games: [{ home: 8, away: 11 }],
    away: ["Basti", "Meik"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Torben", "Meik"],
    games: [{ home: 11, away: 5 }],
    away: ["Basti", "Georg"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Marvin", "Stefan"],
    games: [{ home: 10, away: 11 }],
    away: ["Melf", "Hansi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Marvin", "Melf"],
    games: [{ home: 9, away: 11 }],
    away: ["Stefan", "Hansi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Marvin", "Hansi"],
    games: [{ home: 9, away: 11 }],
    away: ["Stefan", "Melf"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Jasmin", "Sina"],
    games: [{ home: 8, away: 11 }],
    away: ["Qian", "Peng"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Jasmin", "Qian"],
    games: [{ home: 8, away: 11 }],
    away: ["Sina", "Peng"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Jasmin", "Peng"],
    games: [{ home: 8, away: 11 }],
    away: ["Sina", "Qian"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Verena", "Irmtraud"],
    games: [{ home: 5, away: 11 }],
    away: ["Jing", "Gabi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Verena", "Jing"],
    games: [{ home: 7, away: 11 }],
    away: ["Irmtraud", "Gabi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Verena", "Gabi"],
    games: [{ home: 11, away: 10 }],
    away: ["Irmtraud", "Jing"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Martin", "Michael"],
    games: [{ home: 8, away: 11 }],
    away: ["Tuan", "Xuegang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Martin", "Tuan"],
    games: [{ home: 11, away: 7 }],
    away: ["Michael", "Xuegang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Martin", "Xuegang"],
    games: [{ home: 9, away: 11 }],
    away: ["Michael", "Tuan"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Gabi", "Meik"],
    games: [{ home: 10, away: 11 }],
    away: ["Peng", "Hansi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Gabi", "Peng"],
    games: [{ home: 9, away: 11 }],
    away: ["Meik", "Hansi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Gabi", "Hansi"],
    games: [{ home: 11, away: 8 }],
    away: ["Meik", "Peng"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Qian"],
    games: [{ home: 11, away: 5 }],
    away: ["Sina", "Stefan"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Sina"],
    games: [{ home: 11, away: 9 }],
    away: ["Qian", "Stefan"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Stefan"],
    games: [{ home: 11, away: 5 }],
    away: ["Qian", "Sina"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Melf", "Torben"],
    games: [{ home: 11, away: 3 }],
    away: ["Jing", "Michael"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Melf", "Jing"],
    games: [{ home: 5, away: 11 }],
    away: ["Torben", "Michael"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Melf", "Michael"],
    games: [{ home: 11, away: 10 }],
    away: ["Torben", "Jing"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Pengyang", "Georg"],
    games: [{ home: 10, away: 11 }],
    away: ["Martin", "Irmtraud"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Pengyang", "Martin"],
    games: [{ home: 11, away: 7 }],
    away: ["Georg", "Irmtraud"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Pengyang", "Irmtraud"],
    games: [{ home: 2, away: 11 }],
    away: ["Georg", "Martin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Xuegang", "Basti"],
    games: [{ home: 11, away: 2 }],
    away: ["Verena", "Jasmin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Xuegang", "Verena"],
    games: [{ home: 11, away: 10 }],
    away: ["Basti", "Jasmin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Xuegang", "Jasmin"],
    games: [{ home: 11, away: 9 }],
    away: ["Basti", "Verena"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Gabi"],
    games: [{ home: 11, away: 6 }],
    away: ["Qian", "Stefan"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Qian"],
    games: [{ home: 11, away: 5 }],
    away: ["Gabi", "Stefan"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Stefan"],
    games: [{ home: 11, away: 2 }],
    away: ["Gabi", "Qian"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Hansi"],
    games: [{ home: 6, away: 11 }],
    away: ["Peng", "Sina"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Peng"],
    games: [{ home: 11, away: 4 }],
    away: ["Hansi", "Sina"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Sina"],
    games: [{ home: 10, away: 11 }],
    away: ["Hansi", "Peng"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Melf", "Zhenqiang"],
    games: [{ home: 11, away: 2 }],
    away: ["Torben", "Irmtraud"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Melf", "Torben"],
    games: [{ home: 11, away: 9 }],
    away: ["Zhenqiang", "Irmtraud"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Melf", "Irmtraud"],
    games: [{ home: 11, away: 6 }],
    away: ["Zhenqiang", "Torben"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Pengyang", "Michael"],
    games: [{ home: 9, away: 11 }],
    away: ["Georg", "Verena"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Pengyang", "Georg"],
    games: [{ home: 5, away: 11 }],
    away: ["Michael", "Verena"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Pengyang", "Verena"],
    games: [{ home: 5, away: 11 }],
    away: ["Michael", "Georg"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Jing", "Martin"],
    games: [{ home: 8, away: 11 }],
    away: ["Basti", "Marvin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Jing", "Basti"],
    games: [{ home: 11, away: 5 }],
    away: ["Martin", "Marvin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Jing", "Marvin"],
    games: [{ home: 4, away: 11 }],
    away: ["Martin", "Basti"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Hansi"],
    games: [{ home: 4, away: 11 }],
    away: ["Meik", "Melf"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Meik"],
    games: [{ home: 11, away: 8 }],
    away: ["Hansi", "Melf"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Melf"],
    games: [{ home: 8, away: 11 }],
    away: ["Hansi", "Meik"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Gabi", "Xuegang"],
    games: [{ home: 11, away: 10 }],
    away: ["Peng", "Stefan"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Gabi", "Peng"],
    games: [{ home: 11, away: 7 }],
    away: ["Xuegang", "Stefan"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Gabi", "Stefan"],
    games: [{ home: 7, away: 11 }],
    away: ["Xuegang", "Peng"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Sina", "Martin"],
    games: [{ home: 11, away: 5 }],
    away: ["Torben", "Pengyang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Sina", "Torben"],
    games: [{ home: 11, away: 1 }],
    away: ["Martin", "Pengyang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Sina", "Pengyang"],
    games: [{ home: 0, away: 11 }],
    away: ["Martin", "Torben"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Michael"],
    games: [{ home: 11, away: 9 }],
    away: ["Irmtraud", "Basti"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Irmtraud"],
    games: [{ home: 7, away: 11 }],
    away: ["Michael", "Basti"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Basti"],
    games: [{ home: 11, away: 3 }],
    away: ["Michael", "Irmtraud"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Zhenqiang", "Georg"],
    games: [{ home: 9, away: 11 }],
    away: ["Jasmin", "Marvin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Zhenqiang", "Jasmin"],
    games: [{ home: 11, away: 6 }],
    away: ["Georg", "Marvin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Zhenqiang", "Marvin"],
    games: [{ home: 11, away: 10 }],
    away: ["Georg", "Jasmin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Hansi"],
    games: [{ home: 9, away: 11 }],
    away: ["Gabi", "Michael"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Gabi"],
    games: [{ home: 7, away: 11 }],
    away: ["Hansi", "Michael"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Tuan", "Michael"],
    games: [{ home: 7, away: 11 }],
    away: ["Hansi", "Gabi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Melf"],
    games: [{ home: 11, away: 10 }],
    away: ["Peng", "Xuegang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Peng"],
    games: [{ home: 11, away: 3 }],
    away: ["Melf", "Xuegang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Xuegang"],
    games: [{ home: 11, away: 8 }],
    away: ["Melf", "Peng"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Stefan", "Martin"],
    games: [{ home: 11, away: 10 }],
    away: ["Jing", "Jasmin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Stefan", "Jing"],
    games: [{ home: 4, away: 11 }],
    away: ["Martin", "Jasmin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Stefan", "Jasmin"],
    games: [{ home: 11, away: 10 }],
    away: ["Martin", "Jing"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Basti", "Sina"],
    games: [{ home: 11, away: 9 }],
    away: ["Zhenqiang", "Pengyang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Basti", "Zhenqiang"],
    games: [{ home: 11, away: 4 }],
    away: ["Sina", "Pengyang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Basti", "Pengyang"],
    games: [{ home: 5, away: 11 }],
    away: ["Sina", "Zhenqiang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Torben"],
    games: [{ home: 11, away: 3 }],
    away: ["Verena", "Marvin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Verena"],
    games: [{ home: 3, away: 11 }],
    away: ["Torben", "Marvin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Marvin"],
    games: [{ home: 11, away: 6 }],
    away: ["Torben", "Verena"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Xuegang"],
    games: [{ home: 11, away: 6 }],
    away: ["Hansi", "Michael"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Hansi"],
    games: [{ home: 11, away: 8 }],
    away: ["Xuegang", "Michael"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Michael"],
    games: [{ home: 9, away: 11 }],
    away: ["Xuegang", "Hansi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Peng", "Tuan"],
    games: [{ home: 5, away: 11 }],
    away: ["Melf", "Gabi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Peng", "Melf"],
    games: [{ home: 11, away: 7 }],
    away: ["Tuan", "Gabi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Peng", "Gabi"],
    games: [{ home: 10, away: 11 }],
    away: ["Tuan", "Melf"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Basti", "Torben"],
    games: [{ home: 11, away: 4 }],
    away: ["Jasmin", "Pengyang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Basti", "Jasmin"],
    games: [{ home: 8, away: 11 }],
    away: ["Torben", "Pengyang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Basti", "Pengyang"],
    games: [{ home: 9, away: 11 }],
    away: ["Torben", "Jasmin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Sina", "Verena"],
    games: [{ home: 11, away: 8 }],
    away: ["Marvin", "Irmtraud"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Sina", "Marvin"],
    games: [{ home: 11, away: 8 }],
    away: ["Verena", "Irmtraud"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Sina", "Irmtraud"],
    games: [{ home: 11, away: 9 }],
    away: ["Verena", "Marvin"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Zhenqiang"],
    games: [{ home: 11, away: 7 }],
    away: ["Georg", "Jing"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Georg"],
    games: [{ home: 7, away: 11 }],
    away: ["Zhenqiang", "Jing"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Jing"],
    games: [{ home: 7, away: 11 }],
    away: ["Zhenqiang", "Georg"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Peng"],
    games: [{ home: 11, away: 7 }],
    away: ["Tuan", "Michael"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Tuan"],
    games: [{ home: 11, away: 6 }],
    away: ["Peng", "Michael"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Meik", "Michael"],
    games: [{ home: 11, away: 9 }],
    away: ["Peng", "Tuan"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Hansi", "Sina"],
    games: [{ home: 9, away: 11 }],
    away: ["Melf", "Gabi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Hansi", "Melf"],
    games: [{ home: 11, away: 7 }],
    away: ["Sina", "Gabi"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Hansi", "Gabi"],
    games: [{ home: 8, away: 11 }],
    away: ["Sina", "Melf"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Basti", "Martin"],
    games: [{ home: 11, away: 9 }],
    away: ["Zhenqiang", "Verena"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Basti", "Zhenqiang"],
    games: [{ home: 9, away: 11 }],
    away: ["Martin", "Verena"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Basti", "Verena"],
    games: [{ home: 4, away: 11 }],
    away: ["Martin", "Zhenqiang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Marvin"],
    games: [{ home: 11, away: 1 }],
    away: ["Jing", "Pengyang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Jing"],
    games: [{ home: 11, away: 8 }],
    away: ["Marvin", "Pengyang"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Qian", "Pengyang"],
    games: [{ home: 4, away: 11 }],
    away: ["Marvin", "Jing"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Stefan", "Jasmin"],
    games: [{ home: 11, away: 10 }],
    away: ["Georg", "Irmtraud"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Stefan", "Georg"],
    games: [{ home: 11, away: 6 }],
    away: ["Jasmin", "Irmtraud"],
    date: "2022.07.29 Doppel",
  },
  {
    home: ["Stefan", "Irmtraud"],
    games: [{ home: 8, away: 11 }],
    away: ["Jasmin", "Georg"],
    date: "2022.07.29 Doppel",
  },
];
